const GAME_ROUNDS_NUMBER = 10;
const MAX_LIVE = 3;

const POINTS = {
  CORRECT_ANSWER: 100,
  FAST_ANSWER_BONUS: 50,
  SLOW_ANSWER_PENALTY: 50,
  REMAINING_LIVE_BONUS: 50
};

export {
  GAME_ROUNDS_NUMBER,
  MAX_LIVE,
  POINTS
};
